// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcOGm5cIyM9X1RTcOvp1VW97WB51CjFSY',
    appId: '1:1045496146114:web:c7e1f1ffa4d7330975335b',
    messagingSenderId: '1045496146114',
    projectId: 'flutterauth-9811d',
    authDomain: 'flutterauth-9811d.firebaseapp.com',
    storageBucket: 'flutterauth-9811d.appspot.com',
    measurementId: 'G-410SRYCD8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiTqtVq2f0s-UqzMf8j-4dFScWvQk2XNo',
    appId: '1:1045496146114:android:656cff63a141b76775335b',
    messagingSenderId: '1045496146114',
    projectId: 'flutterauth-9811d',
    storageBucket: 'flutterauth-9811d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwO7R20K1u8f-ScRSf8-21M7Lc4WhMNwY',
    appId: '1:1045496146114:ios:6f28e289e68e245a75335b',
    messagingSenderId: '1045496146114',
    projectId: 'flutterauth-9811d',
    storageBucket: 'flutterauth-9811d.appspot.com',
    iosBundleId: 'com.example.onbordingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwO7R20K1u8f-ScRSf8-21M7Lc4WhMNwY',
    appId: '1:1045496146114:ios:c7f28c813ef7f91b75335b',
    messagingSenderId: '1045496146114',
    projectId: 'flutterauth-9811d',
    storageBucket: 'flutterauth-9811d.appspot.com',
    iosBundleId: 'com.example.onbordingScreen.RunnerTests',
  );
}
